# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('futbokas', '0004_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='crt',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='futbokas.Category'),
            preserve_default=False,
        ),
    ]
